CREATE TABLE IF NOT EXISTS user
(
    id
    INTEGER
    GENERATED
    BY
    DEFAULT AS
    IDENTITY
    PRIMARY
    KEY,
    name
    varchar
(
    50
)
    );


CREATE TABLE films
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     varchar(40) NOT NULL,
    produced  integer     NOT NULL,
    date_prod date,
    kind      varchar(10),
    len_min   integer
); 